/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as LangBlogIndexRouteImport } from './routes/$lang/blog/index'
import { Route as LangBlogSlugRouteImport } from './routes/$lang/blog/$slug'
import { Route as LangDocsSplatRouteImport } from './routes/$lang/docs/$'
import { Route as LangDocsChar123Char125DotmdRouteImport } from './routes/$lang/docs/{$}[.]md'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LangBlogIndexRoute = LangBlogIndexRouteImport.update({
  id: '/$lang/blog/',
  path: '/$lang/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangBlogSlugRoute = LangBlogSlugRouteImport.update({
  id: '/$lang/blog/$slug',
  path: '/$lang/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsSplatRoute = LangDocsSplatRouteImport.update({
  id: '/$lang/docs/$',
  path: '/$lang/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsChar123Char125DotmdRoute =
  LangDocsChar123Char125DotmdRouteImport.update({
    id: '/$lang/docs/{$}.md',
    path: '/$lang/docs/{$}.md',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/docs/{$}.md': typeof LangDocsChar123Char125DotmdRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/$lang': typeof LangIndexRoute
  '/blog': typeof BlogIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/docs/{$}.md': typeof LangDocsChar123Char125DotmdRoute
  '/$lang/blog': typeof LangBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/docs/{$}.md': typeof LangDocsChar123Char125DotmdRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/search'
    | '/blog/$slug'
    | '/$lang/'
    | '/blog/'
    | '/$lang/blog/$slug'
    | '/$lang/docs/$'
    | '/$lang/docs/{$}.md'
    | '/$lang/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/search'
    | '/blog/$slug'
    | '/$lang'
    | '/blog'
    | '/$lang/blog/$slug'
    | '/$lang/docs/$'
    | '/$lang/docs/{$}.md'
    | '/$lang/blog'
  id:
    | '__root__'
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/search'
    | '/blog/$slug'
    | '/$lang/'
    | '/blog/'
    | '/$lang/blog/$slug'
    | '/$lang/docs/$'
    | '/$lang/docs/{$}.md'
    | '/$lang/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSearchRoute: typeof ApiSearchRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LangIndexRoute: typeof LangIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LangBlogSlugRoute: typeof LangBlogSlugRoute
  LangDocsSplatRoute: typeof LangDocsSplatRoute
  LangDocsChar123Char125DotmdRoute: typeof LangDocsChar123Char125DotmdRoute
  LangBlogIndexRoute: typeof LangBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/blog/': {
      id: '/$lang/blog/'
      path: '/$lang/blog'
      fullPath: '/$lang/blog/'
      preLoaderRoute: typeof LangBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/blog/$slug': {
      id: '/$lang/blog/$slug'
      path: '/$lang/blog/$slug'
      fullPath: '/$lang/blog/$slug'
      preLoaderRoute: typeof LangBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/$': {
      id: '/$lang/docs/$'
      path: '/$lang/docs/$'
      fullPath: '/$lang/docs/$'
      preLoaderRoute: typeof LangDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/{$}.md': {
      id: '/$lang/docs/{$}.md'
      path: '/$lang/docs/{$}.md'
      fullPath: '/$lang/docs/{$}.md'
      preLoaderRoute: typeof LangDocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSearchRoute: ApiSearchRoute,
  BlogSlugRoute: BlogSlugRoute,
  LangIndexRoute: LangIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  LangBlogSlugRoute: LangBlogSlugRoute,
  LangDocsSplatRoute: LangDocsSplatRoute,
  LangDocsChar123Char125DotmdRoute: LangDocsChar123Char125DotmdRoute,
  LangBlogIndexRoute: LangBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
